;/*FB_PKG_DELIM*/

__d("CometPageVerificationBadge_page.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometPageVerificationBadge_page",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"is_verified",storageKey:null}],type:"Page",abstractKey:null};a.exports=e}),null);
__d("CometPageVerificationBadge.react",["CometPageVerificationBadge_page.graphql","CometProfileVerificationBadge.react","CometRelay","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=s||(s=o("react"));function c(t){var a=o("react-compiler-runtime").c(4),i=t.page,l=t.shouldBeWhite,s=t.size,c=l===void 0?!1:l,d=o("CometRelay").useFragment(e!==void 0?e:e=n("CometPageVerificationBadge_page.graphql"),i),m=d.id,p=d.is_verified===!0;if(m==null||!p)return null;var _;return a[0]!==m||a[1]!==c||a[2]!==s?(_=u.jsx(r("CometProfileVerificationBadge.react"),{isInverted:c,profileID:m,size:s}),a[0]=m,a[1]=c,a[2]=s,a[3]=_):_=a[3],_}l.default=c}),98);
__d("FDSContactFilled20Icon",["cr:14209"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14209")}),98);
__d("FDSContactFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("709451"),20),u=e;l.default=u}),98);
__d("FDSInternetFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("487622"),20),u=e;l.default=u}),98);
__d("FDSMoreShapesFilled20Icon",["cr:15304"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15304")}),98);
__d("FDSMoreShapesFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("966291"),20),u=e;l.default=u}),98);
__d("PagesCometAdminEditingInlineFieldQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9944809835555502"}),null);
__d("PagesCometAdminEditingInlineFieldQuery$Parameters",["PagesCometAdminEditingInlineFieldQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PagesCometAdminEditingInlineFieldQuery_facebookRelayOperation"),metadata:{},name:"PagesCometAdminEditingInlineFieldQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PagesCometAdminEditingInlineField.entrypoint",["JSResourceForInteraction","PagesCometAdminEditingInlineFieldQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeProps,n=e.endPoint,o=e.entryPoint,a=e.field,i=e.pageID;return{extraProps:t,queries:{queryRef:{parameters:r("PagesCometAdminEditingInlineFieldQuery$Parameters"),variables:{endPoint:n,entryPoint:o,field:a,pageID:i,scale:1}}}}},root:r("JSResourceForInteraction")("PagesCometAdminEditingInlineField.react").__setRef("PagesCometAdminEditingInlineField.entrypoint")};l.default=e}),98);
__d("PagesCometAdminEditPageFieldButton.react",["fbt","CometEntryPointDialogTrigger.react","CometPressable.react","FDSButton.react","FDSIcon.react","FDSLink.react","FDSPencilFilled20Icon","PagesCometAdminEditingInlineField.entrypoint","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react"));function c(e){var t=o("react-compiler-runtime").c(18),n=e.createPageUsernameDialog,a=e.customDialogTitle,i=e.endPoint,l=e.entryPoint,c=e.field,d=e.icon,m=e.label,p=e.pageID,_=e.useIcon,f=e.useLink,g=n===void 0?!1:n,h=_===void 0?!1:_,y=f===void 0?!1:f,C;t[0]===Symbol.for("react.memo_cache_sentinel")?(C=s._(/*BTDS*/"Edit Page info"),t[0]=C):C=t[0];var b=C,v,S;t[1]===Symbol.for("react.memo_cache_sentinel")?(v={},S={},t[1]=v,t[2]=S):(v=t[1],S=t[2]);var R;t[3]!==g||t[4]!==a||t[5]!==i||t[6]!==l||t[7]!==c||t[8]!==p?(R={routeParams:S,routeProps:{createPageUsernameDialog:g,customDialogTitle:a,endPoint:i,entryPoint:l,field:c,pageID:p}},t[3]=g,t[4]=a,t[5]=i,t[6]=l,t[7]=c,t[8]=p,t[9]=R):R=t[9];var L;t[10]!==d||t[11]!==m||t[12]!==h||t[13]!==y?(L=function(t){return y?u.jsx(r("FDSLink.react"),{color_DEPRECATED:"highlight",onClick:t,children:m==null?b:m}):h?u.jsx(r("CometPressable.react"),{"aria-label":m!=null?m:s._(/*BTDS*/"Edit Page info"),focusable:!1,onPress:t,overlayDisabled:!0,children:u.jsx(r("FDSIcon.react"),{color:"highlight",icon:d!=null?d:r("FDSPencilFilled20Icon")})}):u.jsx(r("FDSButton.react"),{icon:d,label:m==null?b:m,onPress:t,type:"secondary"})},t[10]=d,t[11]=m,t[12]=h,t[13]=y,t[14]=L):L=t[14];var E;return t[15]!==R||t[16]!==L?(E=u.jsx(r("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:r("PagesCometAdminEditingInlineField.entrypoint"),otherProps:v,preloadParams:R,children:L}),t[15]=R,t[16]=L,t[17]=E):E=t[17],E}l.default=c}),226);
__d("PagesCometAdminEditingSectionDialogQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="29540934588884896"}),null);
__d("PagesCometAdminEditingSectionDialogQuery$Parameters",["PagesCometAdminEditingSectionDialogQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PagesCometAdminEditingSectionDialogQuery_facebookRelayOperation"),metadata:{},name:"PagesCometAdminEditingSectionDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PagesCometAdminEditingSectionDialog.entrypoint",["JSResourceForInteraction","PagesCometAdminEditingSectionDialogQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeProps,n=e.endPoint,o=e.entryPoint,a=e.pageID,i=e.section;return{extraProps:t,queries:{queryRef:{parameters:r("PagesCometAdminEditingSectionDialogQuery$Parameters"),variables:{endPoint:n,entryPoint:o,pageID:a,scale:1,section:i}}}}},root:r("JSResourceForInteraction")("PagesCometAdminEditingSectionDialog.react").__setRef("PagesCometAdminEditingSectionDialog.entrypoint")};l.default=e}),98);
__d("PagesCometAdminEditingUtils",["fbt","FBLogger","FDSClockFilled20Icon","FDSContactFilled20Icon","FDSInfoCircleFilled20Icon","FDSLocationFilled20Icon","FDSMegaphoneFilled20Icon","FDSMoreShapesFilled20Icon","cometPushToast"],(function(t,n,r,o,a,i,l,s){"use strict";function e(){o("cometPushToast").cometPushToast({message:s._(/*BTDS*/"Your changes have been saved.")})}function u(e){switch(e){case"BUSINESS_FYI":return{icon:r("FDSMegaphoneFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"COVID-19 FYI"),underlineColor:"var(--accent)"};case"GENERAL":return{icon:r("FDSInfoCircleFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"General"),underlineColor:"var(--accent)"};case"CONTACT":return{icon:r("FDSContactFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"Contact"),underlineColor:"var(--accent)"};case"LOCATION":return{icon:r("FDSLocationFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"Location"),underlineColor:"var(--accent)"};case"HOURS":return{icon:r("FDSClockFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"Hours"),underlineColor:"var(--accent)"};case"EVENT_TIMES":return{icon:r("FDSClockFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"Weekly schedule"),underlineColor:"var(--accent)"};case"MORE":return{icon:r("FDSMoreShapesFilled20Icon"),iconColor:"primary",label:s._(/*BTDS*/"More"),underlineColor:"var(--accent)"};default:throw r("FBLogger")("pages_admin_editing").mustfixThrow("Unsupported Tab: %s Requested.",e)}}function c(){return{friday:[],monday:[],saturday:[],sunday:[],thursday:[],tuesday:[],wednesday:[]}}l.setSavedToast=e,l.getTabConfigurationForSection=u,l.getDefaultHours=c}),226);
__d("isEmail",[],(function(t,n,r,o,a,i){var e=/^[\w!#\$%&\'\*\+\/\=\?\^`\{\|\}~\-]+(:?\.[\w!#\$%&\'\*\+\/\=\?\^`\{\|\}~\-]+)*@(?:[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?$/i;function l(t){return e.test(t)}i.default=l}),66);
__d("validatePhoneNumber",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){var n=t!=null?t:7;return/^[+]?[0-9()\s-.#]{7,25}$/.test(e)&&e.replace(/[^0-9]/g,"").length>=n}i.default=e}),66);