;/*FB_PKG_DELIM*/

__d("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9702573803157362"}),null);
__d("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters",["CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"),metadata:{},name:"CometUnifiedShareSheetEmbedVideoContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometEmbedVideoDialog.entrypoint",["CometUnifiedShareSheetEmbedVideoContentQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.videoID;return{extraProps:{videoID:e},queries:{embedVideoQueryReference:{parameters:n("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters"),variables:{videoID:e}}}}},root:r("JSResourceForInteraction")("CometEmbedVideoDialogRoot.react").__setRef("CometEmbedVideoDialog.entrypoint")};l.default=e}),98);
__d("CometFeedStoryMenuOriginalStoryIDContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(null);l.default=u}),98);
__d("FBNucleusCautionTriangleFilled20.svg.react",["XPlatReactSVG","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs(o("XPlatReactSVG").Svg,babelHelpers.extends({viewBox:"0 0 20 20",width:"1em",height:"1em",fill:"currentColor",title:e.title},e,{children:[e.children!=null&&s.jsx(o("XPlatReactSVG").Defs,{children:e.children}),s.jsx(o("XPlatReactSVG").Path,{d:"M7.189 2.606c1.252-2.16 4.371-2.16 5.624 0l6.093 10.514c1.256 2.167-.308 4.88-2.812 4.88H3.907c-2.504 0-4.067-2.713-2.812-4.88L7.19 2.606zM10.75 7.75a.75.75 0 0 0-1.5 0v3a.75.75 0 0 0 1.5 0v-3zM9.999 15a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._isSVG=!0;var c=u;l.default=c}),98);
__d("FDSArrowsSquareAddFilled24Icon",["cr:14443"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14443")}),98);
__d("FDSArrowsSquareAddFilled24PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("176104"),24),u=e;l.default=u}),98);
__d("XCometCreatorCollaborationInviteControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/collaboration_invite/{video_id}/{secondary_collaborator_id}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometProfessionalDashboardCollaborationHomeControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/professional_dashboard/collaborations/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("groupGeminiPendingPostReminderDecrementUpdater",[],(function(t,n,r,o,a,i){"use strict";function e(e){var t=e.groupID,n=e.store,r=n.get(t);if(r!=null){var o=r.getLinkedRecords("work_group_reminder_list_renderer");if(o!=null){var a=[];for(var i of o){var l=!0;if(i!=null&&i.getValue("__typename")==="CometGroupPendingPostsReminderRenderer"){var s=i.getValue("count");if(typeof s=="number"){var u=Math.max(s-1,0);u>0?i.setValue(u,"count"):l=!1}}l&&a.push(i)}r.setLinkedRecords(a,"work_group_reminder_list_renderer")}}}i.default=e}),66);
__d("groupsCometDeleteNodeFromConnection",["CometRelay","RelayFBConnectionHandler"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a,i=e.get(t);i!=null&&((a=o("RelayFBConnectionHandler").getAllConnectionsWithKey(e,i,r))!=null?a:[]).forEach(function(e){return o("CometRelay").ConnectionHandler.deleteNode(e,n)})}l.default=e}),98);
__d("useCometEmbedVideo",["CometEmbedVideoDialog.entrypoint","react","react-compiler-runtime","useCometEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useRef;function u(e){var t=o("react-compiler-runtime").c(5),n=e.clickPoint,a=e.videoID,i;t[0]!==a?(i={videoID:a},t[0]=a,t[1]=i):i=t[1];var l=i,u=s(null),c=r("useCometEntryPointDialog")(r("CometEmbedVideoDialog.entrypoint"),l),d=c[0],m;if(t[2]!==n||t[3]!==d){var p=function(){d({clickPoint:n})};m={onClick:p,triggerRef:u},t[2]=n,t[3]=d,t[4]=m}else m=t[4];return m}l.default=u}),98);
__d("viewerContentUpdaterUtils",["CometRelay"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a=e.get(t);if(a!=null){var i;r==="PENDING"?i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"}):r==="PUBLISHED"&&(i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPublishedPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"})),i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,a)}}function s(e,t,n){var r,o=t.getDataID(),a=(r=e.get(o))==null?void 0:r.getLinkedRecord("stories",{content_type:n});if(a!=null){var i=a.getDataID(),l=e.get(i);if(l!=null){var s=l.getValue("count_up_to",{max:51});typeof s=="number"&&l.setValue(Math.max(s-1,0),"count_up_to",{max:51});var u=l.getValue("count_up_to",{max:1});typeof u=="number"&&typeof s=="number"&&s-1===0&&l.setValue(Math.max(u-1,0),"count_up_to",{max:1})}}}l.addEdgeToViewerContentConnection=e,l.decrementSectionCounts=s}),98);
__d("viewerContentPendingPostUpdater",["CometRelay","groupsCometDeleteNodeFromConnection","viewerContentUpdaterUtils"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=e.groupID,n=e.store,a=e.storyID;if(t!=null){var i=n.get(t);if(i!=null){var l=i.getLinkedRecord("viewer_content");if(l!=null){var s=l.getDataID();r("groupsCometDeleteNodeFromConnection")(n,s,a,"GroupsCometViewerContentPendingPostsFeed_stories"),o("viewerContentUpdaterUtils").decrementSectionCounts(n,l,"PENDING")}}}}function s(e,t){return function(n){if(t!=null){var r=n.get(e);if(r!=null){var a=r.getLinkedRecord("viewer_content");if(a!=null){var i=o("CometRelay").ConnectionHandler.getConnection(a,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:"PENDING",ordering:"NEWEST_FIRST"});i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,t)}}}}}l.viewerContentDeletePendingPostUpdater=e,l.viewerContentAddPendingPostUpdater=s}),98);