;/*FB_PKG_DELIM*/

__d("FBReelsClosedCaptionContextProvider",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.createContext,d=u.useContext,m=u.useMemo,p=u.useState,_=c({isCaptionsVisible:null,selectedLocale:null,setIsCaptionsVisible:function(){},setSelectedLocale:function(){}});function f(e){var t=o("react-compiler-runtime").c(6),n=e.children,r=p(""),a=r[0],i=r[1],l=p(null),u=l[0],c=l[1],d;t[0]!==u||t[1]!==a?(d={isCaptionsVisible:u,selectedLocale:a,setIsCaptionsVisible:c,setSelectedLocale:i},t[0]=u,t[1]=a,t[2]=d):d=t[2];var m=d,f;return t[3]!==n||t[4]!==m?(f=s.jsx(_.Provider,{value:m,children:n}),t[3]=n,t[4]=m,t[5]=f):f=t[5],f}function g(){return d(_)}l.FBReelsClosedCaptionContextProvider=f,l.useFBReelsClosedCaptionContext=g}),98);
__d("FBReelsConstants",["fbt","FDSLink.react","react"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=r("react")),c=9/16,d=50,m=900,p="reelsProfile",_=56,f=800,g=s._(/*BTDS*/"Disable Remixing?"),h=s._(/*BTDS*/"Enable Remixing?"),y={aggregation_page:"aggregation_page",bookmark:"fb_shorts_bookmark",ifu:"native_in_feed_unit",notification:"notification",reshare_single_unit:"reshare_feed_unit",scoped_search:"scoped_search",single_unit:"creation_feed_unit",unified_tofu:"unified_tofu",url:"creation_feed_unit"},C=u.jsx(r("FDSLink.react"),{"aria-label":s._(/*BTDS*/"Learn more about remixing reels"),color_DEPRECATED:"highlight",href:"/help/1633654236824653/?helpref=uf_share",target:"_blank",children:s._(/*BTDS*/"Learn More")}),b=s._(/*BTDS*/"No one will be able to create new video remixes with this reel. Existing remixes will not be affected unless you delete your reel. Disabling remixing doesn\u2019t affect your original audio, which anyone can use. It also does not affect your remix setting for any future reels. {Help Center Link}",[s._param("Help Center Link",C)]),v=s._(/*BTDS*/"When you enable remixing, anyone can create reels that play your video and theirs side-by-side. When someone remixes your reel, they can also download your video as part of their remix. You can disable remixing anytime. {Help Center Link}",[s._param("Help Center Link",C)]);l.MEDIA_ASPECT_RATIO=c,l.MIN_VIEWER_HEIGHT=d,l.VIEWER_WIDTH_THRESHOLD=m,l.MESSENGER_WEB_ENTRYPOINT_TYPE=p,l.APP_HEADER_HEIGHT=_,l.WINDOW_HEIGHT_FOR_NON_OVERLAPPED_VIEWER_UFI=f,l.DISABLE_REMIX_TITLE=g,l.ENABLE_REMIX_TITLE=h,l.SOURCE_TO_REFERRAL_SOURCE=y,l.DISABLE_REMIX_BODY=b,l.ENABLE_REMIX_BODY=v}),226);
__d("FBReelsFeedConnectionIDContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={connectionID:""},c=s.createContext(u);l.default=c}),98);
__d("FBReelsHideReelContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={addHiddenReel:function(t){},hiddenReels:null,lastHiddenReel:null,removeHiddenReel:function(t){}},c=s.createContext(u);l.default=c}),98);
__d("FBReelsNodeIndexContextProvider.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={index:0,nodesSize:0,numOfHiddenReel:0,setIndex:function(){}},c=s.createContext(u);l.default=c}),98);
__d("FDSBookmarkCrossOutline20Icon",["cr:14545"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14545")}),98);
__d("FDSBookmarkCrossOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("880859"),20),u=e;l.default=u}),98);
__d("FDSBookmarkFilled20Icon",["cr:14547"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14547")}),98);
__d("FDSBookmarkFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("495598"),20),u=e;l.default=u}),98);
__d("FDSBookmarkOutline20Icon",["cr:14550"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14550")}),98);
__d("FDSBookmarkOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("495628"),20),u=e;l.default=u}),98);
__d("FDSBoxFilled20Icon",["cr:14558"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14558")}),98);
__d("FDSBoxFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("637461"),20),u=e;l.default=u}),98);
__d("FDSCodeOutline20Icon",["cr:14751"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14751")}),98);
__d("FDSCodeOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("498857"),20),u=e;l.default=u}),98);
__d("FDSTranslateOutline20Icon",["cr:15802"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15802")}),98);
__d("FDSTranslateOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("1107407"),20),u=e;l.default=u}),98);