;/*FB_PKG_DELIM*/

__d("FBNucleusMinusFilled16Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 16 16",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M3 8a1 1 0 0 1 1-1h8a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=16,u._isSVG=!0;var c=u;l.default=c}),98);
__d("FDSCalendarAddFilled20Icon",["cr:14606"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14606")}),98);
__d("FDSCalendarAddFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("640913"),20),u=e;l.default=u}),98);
__d("FDSFriendConfirmFilled20Icon",["cr:14220"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14220")}),98);
__d("FDSFriendConfirmFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("538342"),20),u=e;l.default=u}),98);
__d("FDSFriendRemoveFilled20Icon",["cr:15002"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15002")}),98);
__d("FDSFriendRemoveFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("714636"),20),u=e;l.default=u}),98);
__d("FDSWatchTvFilled20Icon",["cr:15866"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15866")}),98);
__d("FDSWatchTvFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("607169"),20),u=e;l.default=u}),98);
__d("VideoPlayerHTML5ApiWebVttState",["Bootloader","FBLogger"],(function(t,n,r,o,a,i,l){"use strict";var e=(function(){function e(e){var t=this,n=e.onReady,o=e.onCaptionsLoaded,a=e.captionsDisplay;this.$1=null,this.source=null,this.captionsDisplay=null,this.$1=r("Bootloader").loadModules(["VideoPlayerWebVttCaptionsSource"],function(e){var r=new e({onCaptionsLoaded:o,onCaptionsChanged:function(n,r){t.captionsDisplay&&t.captionsDisplay.handleCaptionsChanged(n,r)}});t.source=r,t.captionsDisplay=a,n(t)},"VideoPlayerHTML5ApiWebVttState")}var t=e.prototype;return t.loadFromUrl=function(t){var e=this.source;if(!e)throw r("FBLogger")("video_captions").mustfixThrow("[VideoPlayerHTML5ApiWebVttState] Called loadFromUrl when not ready; call from onReady callback.");e.loadFromUrl(t)},t.getCurrentScreenRepresentation=function(){return this.source?this.source.getCurrentScreenRepresentation():null},t.destroy=function(){this.$1&&(this.$1.remove(),this.$1=null),this.captionsDisplay&&(this.captionsDisplay.destroy(),this.captionsDisplay=null),this.source&&(this.source.destroy(),this.source=null)},e})();l.default=e}),98);
__d("WebBloksSSRUtils",[],(function(t,n,r,o,a,i){var e=!!(typeof window!="undefined"&&window.document&&window.document.createElement);i.canUseDOM=e}),66);
__d("differenceSets",[],(function(t,n,r,o,a,i){"use strict";function e(e){for(var t=new Set,n=arguments.length,r=new Array(n>1?n-1:0),o=1;o<n;o++)r[o-1]=arguments[o];e:for(var a of e){for(var i of r)if(i.has(a))continue e;t.add(a)}return t}i.default=e}),66);
__d("mapMapToArray",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){var n=[],r=0;for(var o of e){var a=o[0],i=o[1];n.push(t(i,a,r,e)),r++}return n}i.default=e}),66);
__d("mapSet",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){var n=new Set;for(var r of e)n.add(t(r));return n}i.default=e}),66);
__d("useForceUpdate",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useReducer;function u(){var e=s(c,0),t=e[1];return t}function c(e){return e+1}l.default=u}),98);
__d("useStyleXTransition",["differenceSets","mapMapToArray","mapSet","nullthrows","react","react-compiler-runtime","setImmediate","sortBy","useForceUpdate","useIsMountedRef","useStable"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useEffect,d=s.useLayoutEffect,m=s.useRef,p=window,_=p.clearTimeout,f=p.requestAnimationFrame,g=p.setTimeout;function h(){var e=o("react-compiler-runtime").c(3),t=r("useStable")(y),n;e[0]!==t?(n=function(){return function(){return Array.from(t.values()).forEach(_)}},e[0]=t,e[1]=n):n=e[1];var a;return e[2]===Symbol.for("react.memo_cache_sentinel")?(a=[],e[2]=a):a=e[2],c(n,a),t}function y(){return new Map}function C(){var e=o("react-compiler-runtime").c(3),t=r("useForceUpdate")(),n=r("useIsMountedRef")(),a;return e[0]!==t||e[1]!==n?(a=function(){return function(){n.current&&t()}},e[0]=t,e[1]=n,e[2]=a):a=e[2],r("useStable")(a)}function b(e,t,n,o){var a=C(),i=h(),l=r("useStable")(function(){return new Map}),s=m(!0),c=n.enter,p=n.leave,y=n.base,b=n.duration,v=b===void 0?100:b,S=n.durationIn,R=n.durationOut,L=n.onEnter,E=n.onLeave,k=n.onEnterComplete,I=n.onLeaveComplete,T=u(function(e,t,n){return{item:t,key:e,order:n,xstyle:[y,s.current&&c],style:{transitionDuration:(S!=null?S:v)+"ms"}}},[y,c,S,v]),D=new Map(e.map(function(e,n){return[t(e),{item:e,order:n}]})),x=r("differenceSets")(new Set(D.keys()),new Set(l.keys())),$=r("differenceSets")(new Set(l.keys()),new Set(D.keys())),P=new Map,N=Array.from(r("mapSet")($,function(e){var t=r("nullthrows")(l.get(e)),n=t.order;return n})).sort(function(e,t){return e-t});N.forEach(function(t,n){for(var r=t-n;r<e.length;){var o,a=(o=P.get(r))!=null?o:0;P.set(r,a+1),r+=1}});var M=r("sortBy")([].concat(r("mapMapToArray")(l,function(e){var t=e.key,n=D.get(t);if(n){var r;return babelHelpers.extends({},e,{item:n.item,order:n.order+((r=P.get(n.order))!=null?r:0)})}return e}),Array.from(r("mapSet")(x,function(e){var t=r("nullthrows")(D.get(e)),n=t.item,o=t.order;return T(e,n,o)}))),function(e){return e.order});return d(function(){o!==!0&&(e.forEach(function(e,n){var o,s,u=t(e),d=(o=l.get(u))!=null?o:T(u,e,n);x.has(u)&&f(function(){d.xstyle=[y,c],_(i.get(u)),i.set(u,g(function(){k&&k(e)},S!=null?S:v)),r("setImmediate")(function(){d.xstyle=[y,c],L&&L(e),a()})}),d.item=e,d.order=n+((s=P.get(n))!=null?s:0),l.set(u,d)}),Array.from($.values()).forEach(function(e){var t=l.get(e);if(t!=null){var n=t.item;t.status!=="leaving"&&(t.status="leaving",t.style={transitionDuration:(R!=null?R:v)+"ms"},f(function(){t.xstyle=[y,p],_(i.get(e)),i.set(e,g(function(){l.delete(e),I&&I(n),a()},R!=null?R:v)),r("setImmediate")(function(){E&&E(n),a()})}))}}),s.current=!1)},void 0),M}l.default=b}),98);