;/*FB_PKG_DELIM*/

__d("FDSArrowsLeftRightFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("520619"),20),u=e;l.default=u}),98);
__d("FDSCommentFilled20Icon",["cr:14207"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14207")}),98);
__d("FDSCommentFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("508554"),20),u=e;l.default=u}),98);
__d("FDSPhotoAlbumFilled20Icon",["cr:15404"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15404")}),98);
__d("FDSTrashFilled20Icon",["cr:14101"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14101")}),98);
__d("FDSTrashFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("483826"),20),u=e;l.default=u}),98);
__d("GoodwillAssistedCreationConfigName",[],(function(t,n,r,o,a,i){var e=Object.freeze({DIY:"diy",FATHERS_DAY:"fathers_day",FEED_OVER_THE_YEARS_CHAINING_ON_THIS_DAY:"feed_over_the_years_chaining_on_this_day",FEED_OVER_THE_YEARS_ON_THIS_DAY:"feed_over_the_years_on_this_day",FEED_THEN_AND_NOW_AI_TRANSITION:"feed_then_and_now_ai_transition",FEED_THEN_AND_NOW_ON_THIS_DAY:"feed_then_and_now_on_this_day",FRIEND_BIRTHDAY:"friend_birthday",FRIENDVERSARY:"friendversary",MOTHERS_DAY:"mothers_day",SIBLINGS_DAY:"siblings_day",VALENTINES_DAY:"valentines_day"});i.default=e}),66);
__d("ProfileCometFeaturedPinLimitText",["fbt"],(function(t,n,r,o,a,i,l,s){"use strict";var e=3,u=s._(/*BTDS*/"You can only pin 6 items at a time"),c=s._(/*BTDS*/"_j{\"*\":\"You can only pin {number} items at a time\",\"_1\":\"You can only pin 1 item at a time\"}",[s._plural(e,"number")]);l.MAX_PINNED_ITEMS_UPDATED=e,l.pinLimitErrorText=u,l.updatedPinLimitErrorText=c}),226);
__d("ProfileCometPinnedPostStrings",["fbt"],(function(t,n,r,o,a,i,l,s){"use strict";var e=s._(/*BTDS*/"Unpin post"),u=s._(/*BTDS*/"Pin post"),c=s._(/*BTDS*/"Your post has been unpinned"),d=s._(/*BTDS*/"Your post has been pinned"),m=s._(/*BTDS*/"Please check your internet connection and try again."),p=s._(/*BTDS*/"Something went wrong. Please try again.");l.UNPIN_MENU_ITEM_LABEL=e,l.PIN_MENU_ITEM_LABEL=u,l.POST_UNPINNED_SUCCESS_MESSAGE=c,l.POST_PINNED_SUCCESS_MESSAGE=d,l.PINNED_POST_NETWORK_ERROR_MESSAGE=m,l.PINNED_POST_GENERIC_ERROR_MESSAGE=p}),226);
__d("useGeminiHasNarrowWidth",["gkx","useMatchViewport"],(function(t,n,r,o,a,i,l){"use strict";function e(){var e=r("gkx")("7947"),t=r("gkx")("13381"),n=r("useMatchViewport")("max","width",600);return e&&t&&n}l.default=e}),98);