;/*FB_PKG_DELIM*/

__d("FDSCalendarFilled20Icon",["cr:13822"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13822")}),98);
__d("FDSCalendarFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481118"),20),u=e;l.default=u}),98);
__d("FDSCalendarOutline20Icon",["cr:14621"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14621")}),98);
__d("FDSCalendarOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481127"),20),u=e;l.default=u}),98);
__d("FDSCamcorderFilled20Icon",["cr:14631"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14631")}),98);
__d("FDSCamcorderFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("493174"),20),u=e;l.default=u}),98);
__d("FDSLocationFilled20Icon",["cr:15234"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15234")}),98);
__d("FDSLocationFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("795388"),20),u=e;l.default=u}),98);
__d("FDSPencilFilled20Icon",["cr:14236"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14236")}),98);
__d("FDSPencilFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("477826"),20),u=e;l.default=u}),98);
__d("FDSPhoneFilled20Icon",["cr:15391"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15391")}),98);
__d("FDSPhoneFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("558161"),20),u=e;l.default=u}),98);
__d("FDSPinFilled20Icon",["cr:13887"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13887")}),98);
__d("FDSPinFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481942"),20),u=e;l.default=u}),98);
__d("FDSPostClockFilled20Icon",["cr:15477"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15477")}),98);
__d("FDSPostClockFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("1604445"),20),u=e;l.default=u}),98);
__d("MWFDSPause.svg.react",["cr:21727"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:21727")}),98);
__d("MWFDSPlay.svg.react",["cr:21739"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:21739")}),98);
__d("MWFDSReplay.svg.react",["cr:21757"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:21757")}),98);
__d("MWXIconPause",["MWXSvgIcon","SVGIcon","cr:22421","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=o("MWXSvgIcon").mwxSvgIcon(o("SVGIcon").svgIcon(n("cr:22421")),r("gkx")("23219"));l.default=e}),98);
__d("MWXIconPlay",["MWXSvgIcon","SVGIcon","cr:22437","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=o("MWXSvgIcon").mwxSvgIcon(o("SVGIcon").svgIcon(n("cr:22437")),r("gkx")("23219"));l.default=e}),98);
__d("MWXIconReplay",["MWXSvgIcon","SVGIcon","cr:22459","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=o("MWXSvgIcon").mwxSvgIcon(o("SVGIcon").svgIcon(n("cr:22459")),r("gkx")("23219"));l.default=e}),98);
__d("MWVideoPlayerPlayButton.react",["fbt","MWXIconPause","MWXIconPlay","MWXIconReplay","MWXIconStrict.react","MWXPressable.react","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react")),c={buttonLarge:{height:"xdd8jsf",marginTop:"xuqeo79",marginInlineEnd:"x14z9mp",marginBottom:"xat24cr",marginInlineStart:"x1vvjuq3",width:"xvni27",$$css:!0},buttonSmall:{height:"xxk0z11",marginTop:"x7wgvq7",marginInlineEnd:"x14z9mp",marginBottom:"xat24cr",marginInlineStart:"x18xomjl",width:"xvy4d1p",$$css:!0},circleButton:{backgroundColor:"x18l40ae",borderStartStartRadius:"x1c9tyrk",borderStartEndRadius:"xeusxvb",borderEndEndRadius:"x1pahc9y",borderEndStartRadius:"x1ertn4p",opacity:"x1hc1fzr",$$css:!0},clickable:{cursor:"x1ypdohk",$$css:!0},container:{alignItems:"x6s0dn4",display:"x78zum5",insetInlineStart:"xbudbmw",left:null,right:null,justifyContent:"xl56j7k",position:"x10l6tqk",top:"xwa60dl",$$css:!0}};function d(e){var t=o("react-compiler-runtime").c(9),n=e.alt,a=e.isVisible,i=e.onClick,l=e.size,d=e.type,m=l===void 0?"LARGE":l,p=d===void 0?"PLAY":d,_;e:switch(p){case"PAUSE":{_=r("MWXIconPause");break e}case"REPLAY":{_=r("MWXIconReplay");break e}case"PLAY":default:_=r("MWXIconPlay")}var f=m==="LARGE"?24:12,g;t[0]!==_||t[1]!==f?(g=u.jsx(r("MWXIconStrict.react"),{color:"white",icon:_,size:f}),t[0]=_,t[1]=f,t[2]=g):g=t[2];var h=g,y;t[3]!==n||t[4]!==h||t[5]!==a||t[6]!==i||t[7]!==m?(y=a?i!=null?u.jsx(r("MWXPressable.react"),{display:"inline",label:n!=null?n:s._(/*BTDS*/"Play video"),onPress:i,overlayDisabled:!0,xstyle:[c.circleButton,c.container,c.clickable,m==="LARGE"&&c.buttonLarge,m==="SMALL"&&c.buttonSmall],children:h}):u.jsx("div",babelHelpers.extends({},{0:{className:"x18l40ae x1c9tyrk xeusxvb x1pahc9y x1ertn4p x1hc1fzr x6s0dn4 x78zum5 xbudbmw xl56j7k x10l6tqk xwa60dl"},2:{className:"x18l40ae x1c9tyrk xeusxvb x1pahc9y x1ertn4p x1hc1fzr x6s0dn4 x78zum5 xbudbmw xl56j7k x10l6tqk xwa60dl xdd8jsf xuqeo79 x14z9mp xat24cr x1vvjuq3 xvni27"},1:{className:"x18l40ae x1c9tyrk xeusxvb x1pahc9y x1ertn4p x1hc1fzr x6s0dn4 x78zum5 xbudbmw xl56j7k x10l6tqk xwa60dl xxk0z11 x7wgvq7 x14z9mp xat24cr x18xomjl xvy4d1p"},3:{className:"x18l40ae x1c9tyrk xeusxvb x1pahc9y x1ertn4p x1hc1fzr x6s0dn4 x78zum5 xbudbmw xl56j7k x10l6tqk xwa60dl xxk0z11 x7wgvq7 x14z9mp xat24cr x18xomjl xvy4d1p"}}[(m==="LARGE")<<1|(m==="SMALL")<<0],{children:h})):null,t[3]=n,t[4]=h,t[5]=a,t[6]=i,t[7]=m,t[8]=y):y=t[8];var C=y;return C}l.default=d}),226);
__d("MWXVideoStatusListener.react",["getErrorNameFromMediaErrorCode","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useEffect;function u(e){var t=o("react-compiler-runtime").c(5),n=e.onError,a=e.onLoad,i=e.videoRef,l,u;return t[0]!==n||t[1]!==a||t[2]!==i?(l=function(){var e=i==null?void 0:i.current,t=function(){a==null||a()},o=function(t){var e=t.currentTarget,o=e.error,a=r("getErrorNameFromMediaErrorCode")(o==null?void 0:o.code);n==null||n(a)};if((e==null?void 0:e.readyState)!=null&&e.readyState>=2){t();return}return e==null||e.addEventListener("canplay",t),e==null||e.addEventListener("error",o),(function(){e==null||e.removeEventListener("canplay",t),e==null||e.removeEventListener("error",o)})},u=[n,a,i],t[0]=n,t[1]=a,t[2]=i,t[3]=l,t[4]=u):(l=t[3],u=t[4]),s(l,u),null}l.default=u}),98);
__d("VideoPlayerX.react",["VideoPlayerErrorBoundary.react","VideoPlayerXImpl.react","defaultErrorBoundaryFallback","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e=["doNotRenderErrorBoundaryIUnderstandIMustProvideMyOwn","errorBoundaryFallback"],s,u=s||(s=o("react"));function c(t){var n=o("react-compiler-runtime").c(10),a,i,l;n[0]!==t?(l=t.doNotRenderErrorBoundaryIUnderstandIMustProvideMyOwn,a=t.errorBoundaryFallback,i=babelHelpers.objectWithoutPropertiesLoose(t,e),n[0]=t,n[1]=a,n[2]=i,n[3]=l):(a=n[1],i=n[2],l=n[3]);var s=l===void 0?!1:l,c=i.videoPlayerSpherical!=null,d;n[4]!==i||n[5]!==c?(d=u.jsx(r("VideoPlayerXImpl.react"),babelHelpers.extends({VideoPlayerShakaPerformanceLoggerClass:null,isSpherical:c},i)),n[4]=i,n[5]=c,n[6]=d):d=n[6];var m=d;if(s)return m;var p=a!=null?a:r("defaultErrorBoundaryFallback"),_;return n[7]!==m||n[8]!==p?(_=u.jsx(r("VideoPlayerErrorBoundary.react"),{description:"VideoPlayerX",fallback:p,children:m}),n[7]=m,n[8]=p,n[9]=_):_=n[9],_}l.default=c}),98);
__d("useBaseDynamicEntryPointDialog",["CometDialogContext","CometRelay","CometSuspendedDialogImpl.react","clearTimeout","react","react-compiler-runtime","setTimeout","tracePolicyFromResource","useCometRelayEntrypointContextualEnvironmentProvider"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useCallback,d=u.useContext,m=u.useEffect,p=u.useRef;function _(e){var t=o("react-compiler-runtime").c(17),n=e.entryPoint,a=e.environmentProvider,i=e.onClose,l=e.otherProps,u=e.overrideRelayEnv,c=e.preloadedEntryPoint,d=e.preloadParams,_=o("CometRelay").useEntryPointLoader(a,n),f=_[0],g=_[1],h=_[2],y=f!=null?f:c,C=p(null),b,v;t[0]!==h||t[1]!==y.isDisposed||t[2]!==d||t[3]!==c||t[4]!==g||t[5]!==f?(b=function(){return C.current!=null&&(r("clearTimeout")(C.current),C.current=null),y.isDisposed&&g(d),(function(){C.current=r("setTimeout")(function(){f?h():c.dispose(),C.current=null},6e4)})},v=[h,y.isDisposed,c,d,g,f],t[0]=h,t[1]=y.isDisposed,t[2]=d,t[3]=c,t[4]=g,t[5]=f,t[6]=b,t[7]=v):(b=t[6],v=t[7]),m(b,v);var S;t[8]!==i||t[9]!==l?(S=babelHelpers.extends({},l,{onClose:i}),t[8]=i,t[9]=l,t[10]=S):S=t[10];var R=S,L;t[11]!==c||t[12]!==R?(L=s.jsx(o("CometRelay").EntryPointContainer,{entryPointReference:c,props:R}),t[11]=c,t[12]=R,t[13]=L):L=t[13];var E=L,k;return t[14]!==E||t[15]!==u?(k=u!=null?s.jsx(o("CometRelay").RelayEnvironmentProvider,{environment:u,children:E}):E,t[14]=E,t[15]=u,t[16]=k):k=t[16],k}function f(e,t,n,a){var i=o("react-compiler-runtime").c(7),l=r("useCometRelayEntrypointContextualEnvironmentProvider")(a),s=d(r("CometDialogContext")),u;return i[0]!==s||i[1]!==e||i[2]!==l||i[3]!==n||i[4]!==a||i[5]!==t?(u=function(u,c,d,m,p){var i=o("CometRelay").loadEntryPoint(l,e,u),f=function(){for(var e=arguments.length,t=new Array(e),n=0;n<e;n++)t[n]=arguments[n];var r=t;d&&d.apply(void 0,r),i.dispose()};s(r("CometSuspendedDialogImpl.react"),{dialog:_,dialogProps:{entryPoint:e,environmentProvider:l,otherProps:c,overrideRelayEnv:a,preloadedEntryPoint:i,preloadParams:u},fallback:n},{loadType:"entrypoint",preloadTrigger:t,tracePolicy:m!=null?m:r("tracePolicyFromResource")("comet.dialog",e.root)},f,{replaceCurrentDialog:p})},i[0]=s,i[1]=e,i[2]=l,i[3]=n,i[4]=a,i[5]=t,i[6]=u):u=i[6],u}l.default=f}),98);
__d("useCometDynamicEntryPointDialog",["FDSDialogLoadingState.react","react","useBaseDynamicEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=function(t){return s.jsx(r("FDSDialogLoadingState.react"),{onClose:t})};function c(e,t,n,o){return r("useBaseDynamicEntryPointDialog")(e,t,n!=null?n:u,o)}l.default=c}),98);