;/*FB_PKG_DELIM*/

__d("FBReelsEntityDialogImplQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25843689181903088"}),null);
__d("FBReelsEntityDialogImplQuery$Parameters",["FBReelsEntityDialogImplQuery_facebookRelayOperation","FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider","FBReels_deprecate_short_form_video_context_gk.relayprovider","FBReels_enable_meta_ai_label_gk.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("FBReelsEntityDialogImplQuery_facebookRelayOperation"),metadata:{},name:"FBReelsEntityDialogImplQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReels_deprecate_short_form_video_context_gkrelayprovider:n("FBReels_deprecate_short_form_video_context_gk.relayprovider"),__relay_internal__pv__FBReels_enable_meta_ai_label_gkrelayprovider:n("FBReels_enable_meta_ai_label_gk.relayprovider"),__relay_internal__pv__FBReelsMediaFooter_comet_enable_reels_ads_gkrelayprovider:n("FBReelsMediaFooter_comet_enable_reels_ads_gk.relayprovider")}}};a.exports=e}),null);
__d("FBReelsEntityDialog.entrypoint",["FBReelsEntityDialogImplQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";function e(e){if(e==null)throw new TypeError("Cannot destructure "+e)}var s={getPreloadProps:function(r){var t=babelHelpers.extends({},(e(r),r)),a=o("WebPixelRatio").get();return{queries:{queryReference:{parameters:n("FBReelsEntityDialogImplQuery$Parameters"),variables:babelHelpers.extends({renderLocation:"fb_shorts_profile",scale:a,useDefaultActor:!1},t)}}}},root:r("JSResourceForInteraction")("FBReelsEntityDialog.react").__setRef("FBReelsEntityDialog.entrypoint")};l.default=s}),98);
__d("FDSAudioHiFilled20Icon",["cr:13948"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13948")}),98);
__d("FDSAudioHiFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("564390"),20),u=e;l.default=u}),98);
__d("FDSAudioOffFilled20Icon",["cr:13952"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13952")}),98);
__d("FDSAudioOffFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("564396"),20),u=e;l.default=u}),98);
__d("FDSAudioOffOutline20Icon",["cr:14465"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14465")}),98);
__d("FDSAudioOffOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("564399"),20),u=e;l.default=u}),98);
__d("FDSPlayOutline20Icon",["cr:15447"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15447")}),98);
__d("FDSPlayOutline20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("484866"),20),u=e;l.default=u}),98);