;/*FB_PKG_DELIM*/

__d("CometInstantGamesPlayerRHCQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="31657791750471737"}),null);
__d("CometInstantGamesPlayerRHCQuery$Parameters",["CometInstantGamesPlayerRHCQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometInstantGamesPlayerRHCQuery_facebookRelayOperation"),metadata:{},name:"CometInstantGamesPlayerRHCQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometInstantGamesPlayerRHC.entrypoint",["CometInstantGamesPlayerRHCQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{extraProps:{isFullScreenOverride:t.isFullScreenOverride,productHoldoutHideRHCContent:t.productHoldoutHideRHCContent},queries:{queryReference:{parameters:n("CometInstantGamesPlayerRHCQuery$Parameters"),variables:{app_id:t.appID,has_community:t.hasCommunity&&!t.productHoldoutHideRHCContent,has_rhc:t.hasRHC,is_canvas_on_comet:t.isConC,product_holdout_hide_rhc_content:t.productHoldoutHideRHCContent}}}}},root:r("JSResourceForInteraction")("CometInstantGamesPlayerRHC.react").__setRef("CometInstantGamesPlayerRHC.entrypoint")};l.default=e}),98);
__d("CometInstantGamesPlayerRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25010482145272536"}),null);
__d("CometInstantGamesPlayerRootQuery$Parameters",["CometInstantGamesPlayerRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometInstantGamesPlayerRootQuery_facebookRelayOperation"),metadata:{},name:"CometInstantGamesPlayerRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("InstantApplicationContextTokenInputCreator.entrypointutils",[],(function(t,n,r,o,a,i){"use strict";function e(e,t,n){var r=null;switch(n){case"THREAD":r={thread_id:t};break;case"STORY":r={story_token:t};break;case"GROUP":r={group_id:t};break;case"LINK":r={link_fragment:t};break;default:r=Object.freeze({});break}return{app_id:e,context_source_id:t,key:r}}i.getTokenInput=e}),66);
__d("InstantGameEnvironmentType.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["CANVAS_ON_COMET","COPLAY","EMBEDDED","FBIOS_IAB","LIVE_PRODUCER_PLUGIN","MESSENGER_DISCOVERY","REELS_PLUGIN","STANDARD","UNCONNECTED","VIDEO_PLUGIN"]),l=e;i.default=l}),66);
__d("InstantGameEnvironmentType",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({LIVE_PRODUCER_PLUGIN:"live_producer_plugin",REELS_PLUGIN:"reels_plugin",VIDEO_PLUGIN:"video_plugin",STANDARD:"standard",COPLAY:"coplay",CANVAS_ON_COMET:"canvas_on_comet",FBIOS_IAB:"fbios_iab",MESSENGER_DISCOVERY:"messenger_discovery",UNCONNECTED:"unconnected",EMBEDDED:"embedded"}),l=e;i.default=l}),66);
__d("InstantGameEnvironmentTypeUtils.facebook",["$InternalEnumUtils","InstantGameEnvironmentType"],(function(t,n,r,o,a,i,l){var e=o("$InternalEnumUtils").createToJSEnum(r("InstantGameEnvironmentType")),s=o("$InternalEnumUtils").createFromJSEnum(r("InstantGameEnvironmentType"));l.toJSEnum=e,l.fromJSEnum=s}),98);
__d("InstantGamesPlayer.entrypointutils",[],(function(t,n,r,o,a,i){"use strict";var e=["276641894055477","5377936592235218"];function l(t){return!e.includes(String(t))}function s(e,t){return t&&e!=="canvas_on_comet"}i.HORIZON_2D_APP_IDS=e,i.getHasRHC=l,i.getHasCommunity=s}),66);
__d("CometInstantGamesPlayerRoot.entrypoint",["CometInstantGamesPlayerRHC.entrypoint","CometInstantGamesPlayerRootQuery$Parameters","InstantApplicationContextTokenInputCreator.entrypointutils","InstantGameEnvironmentTypeUtils.facebook","InstantGamesPlayer.entrypointutils","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e,a,i,l,s=(e=o("InstantGameEnvironmentTypeUtils.facebook").fromJSEnum(t.routeProps.environmentType))!=null?e:"STANDARD",u=t.routeProps.productHoldoutDisableRHC?!1:o("InstantGamesPlayer.entrypointutils").getHasRHC(t.routeProps.appID),c=s==="CANVAS_ON_COMET",d=o("InstantApplicationContextTokenInputCreator.entrypointutils").getTokenInput(t.routeProps.appID,t.routeParams.context_source_id,(a=t.routeParams.context_type)!=null?a:"GENERIC"),m=t.routeProps.isCometOnMobile;return{entryPoints:{cometInstantGamesPlayerRHCEntryPoint:o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:r("CometInstantGamesPlayerRHC.entrypoint"),entryPointParams:{appID:t.routeProps.appID,hasCommunity:o("InstantGamesPlayer.entrypointutils").getHasCommunity(t.routeProps.environmentType,u),hasRHC:u,isConC:u&&c,isFullScreenOverride:t.routeProps.isFullScreen,productHoldoutHideRHCContent:t.routeProps.productHoldoutHideRHCContent}})},extraProps:{hasRHC:u},queries:{instantGamesPlayerRootQuery:{options:{},parameters:n("CometInstantGamesPlayerRootQuery$Parameters"),variables:{app_id:t.routeProps.appID,automated_input_config_name:t.routeParams.automated_input_config_name,cgreferral:t.routeParams.cgreferral,cloud_binary_id:t.routeParams.cloud_binary_id,cloud_host_override_cluster:t.routeParams.cloud_host_override_cluster,cloud_host_override_host:t.routeParams.cloud_host_override_host,cloud_host_override_hostname:t.routeParams.cloud_host_override_hostname,cloud_host_override_pop:t.routeParams.cloud_host_override_pop,cloud_host_override_port:t.routeParams.cloud_host_override_port,cloud_host_override_site_key:t.routeParams.cloud_host_override_site_key,context_key:d.key,context_source_id:t.routeParams.context_source_id,environment_type:s,is_canvas_on_comet:c,is_comet_on_mobile:m,ota_update:t.routeParams.ota_update,payload:t.routeParams.payload,session_id:(i=t.routeParams.session_id)!=null?i:(l=t.timeSpentMetaData)==null||(l=l.session_ids)==null?void 0:l.cg_session_id,show_top_bar:!t.routeProps.hideTopBar,skip_desktop_fragment:m,skip_mobile_fragment:!m,source:t.routeProps.source}}}}},root:r("JSResourceForInteraction")("CometInstantGamesPlayerRoot.react").__setRef("CometInstantGamesPlayerRoot.entrypoint")};l.default=e}),98);