;/*FB_PKG_DELIM*/

__d("EventsActionsSrCoreFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1845787"),s=o("FalcoLoggerInternal").create("events_actions_sr_core",e),u=s;l.default=u}),98);
__d("GroupClickActionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("780"),s=o("FalcoLoggerInternal").create("group_click_action",e),u=s;l.default=u}),98);
__d("GroupPostTopicsClientEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1355"),s=o("FalcoLoggerInternal").create("group_post_topics_client_events",e),u=s;l.default=u}),98);
__d("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25294883380162121"}),null);
__d("GroupsCometParticipationQuestionsDialogQuery$Parameters",["GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometParticipationQuestionsDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometParticipationQuestionsDialog.entrypoint",["GroupsCometParticipationQuestionsDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.groupID;return{queries:{queryReference:{parameters:r("GroupsCometParticipationQuestionsDialogQuery$Parameters"),variables:{groupID:e,scale:o("WebPixelRatio").get()}}}}},root:r("JSResourceForInteraction")("GroupsCometParticipationQuestionsDialog.react").__setRef("GroupsCometParticipationQuestionsDialog.entrypoint")};l.default=e}),98);
__d("GroupsCometParticipationQuestionsDialogFbts_group.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometParticipationQuestionsDialogFbts_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};a.exports=e}),null);
__d("GroupsCometParticipationQuestionsDialogFbts",["fbt","GroupsCometParticipationQuestionsDialogFbts_group.graphql"],(function(t,n,r,o,a,i,l,s){"use strict";var e;e!==void 0||(e=n("GroupsCometParticipationQuestionsDialogFbts_group.graphql"));var u=s._(/*BTDS*/"Answer questions"),c=s._(/*BTDS*/"Participation review");l.participationQuestionsDialogTitle=u,l.participationReviewDialogTitle=c}),226);
__d("addLocalGroupFeedInlineMessage",["CometRelay","FBLogger","cometUniqueID"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n){var o=e.get(t);if(o==null){r("FBLogger")("groups_comet").mustfix("Group Feed Inline Message Updater: Could not find group edge in store");return}var a=o.getLinkedRecords("local_feed_inline_messages")||[];o.setLinkedRecords([].concat(a,[n]),"local_feed_inline_messages")}function s(t,n,a){o("CometRelay").commitLocalUpdate(t,function(t){var o="client:LocalGroupFeedVideoInlineMessage:"+r("cometUniqueID")(),i=t.create(o,"LocalGroupFeedVideoInlineMessage");i.setValue(String(o),"id"),i.setValue(String(n),"group_id"),i.setValue(String(a),"message"),e(t,n,i)})}function u(e,t,n){o("CometRelay").commitLocalUpdate(e,function(e){var o=e.get(t);if(o==null){r("FBLogger")("groups_comet").mustfix("Group Feed Inline Message Updater: Could not find group edge in store");return}var a=o.getLinkedRecords("local_feed_inline_messages")||[],i=a.filter(function(e){return(e==null?void 0:e.getDataID())!==n});e.delete(n),o.setLinkedRecords(i,"local_feed_inline_messages")})}l.addLocalVideoFeedMessage=s,l.removeLocalFeedMessage=u}),98);
__d("useGroupsCometIsProfileDelegateGroup_group.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useGroupsCometIsProfileDelegateGroup_group",selections:[{alias:null,args:null,concreteType:"GroupNavigationInfo",kind:"LinkedField",name:"navigation_info",plural:!1,selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"destination",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],storageKey:null}],storageKey:null}],type:"Group",abstractKey:null};a.exports=e}),null);
__d("useGroupsCometIsProfileDelegateGroup",["CometRelay","useGroupsCometIsProfileDelegateGroup_group.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t){var r,a=t.group$key,i=o("CometRelay").useFragment(e!==void 0?e:e=n("useGroupsCometIsProfileDelegateGroup_group.graphql"),a);return((r=i.navigation_info)==null||(r=r.destination)==null?void 0:r.__typename)==="User"}l.default=s}),98);
__d("useGroupsCometParticipationQuestionsEntryPointDialog",["FDSCardedDialogLoadingStateLegacy.react","GroupsCometParticipationQuestionsDialog.entrypoint","GroupsCometParticipationQuestionsDialogFbts","react","react-compiler-runtime","useCometEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=o("react-compiler-runtime").c(2),n=e.groupID,a;return t[0]!==n?(a={groupID:n},t[0]=n,t[1]=a):a=t[1],r("useCometEntryPointDialog")(r("GroupsCometParticipationQuestionsDialog.entrypoint"),a,void 0,c)}function c(e){return s.jsx(r("FDSCardedDialogLoadingStateLegacy.react"),{onClose:e,title:o("GroupsCometParticipationQuestionsDialogFbts").participationQuestionsDialogTitle,withCloseButton:!0})}c.displayName=c.name+" [from "+i.id+"]",l.default=u}),98);